### ISSUE TITLE
Replace custom Git command with a 3rd party package

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/git-artifact#64]
#42 is now complete. This allows to further improve the core.

We need to:
1. Update the core to use https://github.com/czproject/git-php and remove all custom Git commands unless the package does not provide these commands. Maybe even implement own class that extends the class from the package to add more missing methods.
2. Update test to use the same package instead of custom git commands. We want to rely on the package in all parts of the script.

**Comment by tannguyen04** [comment]
Hi @AlexSkrypnyk 

I have analyzed your request as below, could you please review.

- Remove GitWrapper packages.
- Use git-php package and methods from that package.
- Remove GitTrait class, move GitTrait functions into GitArtifactGitRepository class.
- Update tests using methods from GitArtifactGitRepository class.

```
GitArtifactGitRepository extends GitRepository
	- getCurrentBranch
	- switchToBranch
	- removeSubRepos
	- remoteExists
	- push
	- commitAllFiles
	- getTags
	- ...
```

```
GitHelper class
	- public static isValidBranchName
	- public statis IsUri
	- public static isValidRemote
	- public static isValidLocalRemote
	- public static isValidUriRemote
```

**Comment by AlexSkrypnyk** [comment]
@tannguyen04 
something like that, but `GitArtifactGitRepository` would contain everything from `GitHelper` class and would not contain duplicated methods that `GitRepository` provides. We do not need to have 2 classes dealing with Git. One class is enough.
